//0
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.0.99.0")]
[assembly: AssemblyVersion("1.0.99.0")]
[assembly: AssemblyInformationalVersion("v1.0.99")]
[assembly: KSPAssembly("NyanCat", 1,0,99)]

namespace NyanCat
{
	public static class Version
	{
		public const int major = 1;
		public const int minor = 0;
		public const int patch = 99;
		public const int build = 0;
		public const string Number = "1.0.99.0";
#if DEBUG
        public const string Text = Number + "-zed'K BETA DEBUG";
#else
        public const string Text = Number + "-zed'K";
#endif
	}
}